includable/react-native-email-link

- README.md
Hey, linking information was missing for android, which caused me to think the library was not working.
Just added it to the readme
> Update README with linking information

- android/src/main/java/com/facebook/react/modules/email/EmailModule.java
We've gotten a few reports in Sentry about our App crashing coming from this library.  I've written a fix for this. The drawback of this change is that the user will not get any feedback, but the method will not crash the app anymore. No window displaying possible apps to run is shown anymore. If you want a good view of the changes, i suggest using the ignore whitespace option (use the gear icon).  
```txt
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference
at android.content.Intent.createChooser(Intent.java:930)
at android.content.Intent.createChooser(Intent.java:891)
at com.facebook.react.modules.email.EmailModule.open(EmailModule.java:42)
at java.lang.reflect.Method.invoke(Method.java)
at …
```
> Added additional null check to prevent App crash

- .gitignore
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/facebook/react/modules/email/EmailPackage.java
- package.json
I couldn't get the forked version of the repo to build in my pretty up-to-date android studio setup. So I went down the rabbit hole of cleaning up the build.gradle file to get it working. 
Resolves https://github.com/tschoffelen/react-native-email-link/issues/36
Additionally, I'm not 100% sure if this is the only thing needed for AndroidX support, but I at least updated the target version to 29: https://github.com/tschoffelen/react-native-email-link/issues/25
> Update the android project to build

- README.md
- android/src/main/java/com/facebook/react/modules/email/EmailModule.java
- index.android.js
Adds an optional param `newTask` for the Android version of the API. Setting it explicitly to `false` will start the activity in the current Android task. It's an optional param, with a default value of `true`.
Resolves https://github.com/leanmotherfuckers/react-native-email-link/issues/29
Attempt 2 for https://github.com/tschoffelen/react-native-email-link/pull/30
> Android: add an optional param to start the activity in the current task

- README.md
- index.d.ts
- index.ios.js
Being able to open the mail app to the compose screen and optionally provide `to`, `cc`, `bcc`, `subject` and `body`.
It has only been implemented for iOS so far. I've tested it on my iPhone 7 device with Gmail and Apple Mail. It's working as expected.
I added new attributes to the options argument of `openInbox()`.
| param | required | default | description |
| --- | --- | --- | --- |
|compose| no | `false` | When set to `true`, it will force the app to open on the compose screen even if you do not provide any of the following attributes: **to**, **cc**, **bcc**, **subject** or **body**. If you do provide at least one of these attributes, the app will by default be opened on the compose screen so no need to set this attribute to `true` in this case.|
| to | no | `undefined` | The email …
> Open the mail app on the compose screen

- android/build.gradle
The latest version of the library is failing to build on Android with the following error:
`Cannot get property 'reactNativeVersion' on extra properties extension as it does not exist`
This PR fixes that by having a safeExtGet, where if `reactNativeVersion` is present it will take that and `+` otherwise
> Latest release failing on Android because reactNativeVersion not found

- android/src/main/java/com/facebook/react/modules/email/EmailPackage.java
This PR removes the Override in on the `createJSModules` call. For more information: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
I have tested and everything works fine on RNv0.61.2.
> Remove override of createJSModules

- index.ios.js
[This PR](https://github.com/tschoffelen/react-native-email-link/pull/31) removed compatibility with those two email clients. In case that was done by mistake, this tries to bring it back.
> Add compatibility with yahoo and superhuman

- index.d.ts
The implementation of both `openInbox` and `openComposer` are `async`, which means the function returns a promise (not `void`). This PR corrects the typescript definitions of these functions, so Typescript projects that consume this library can call `await openInbox({ ... })` without getting warned by the transpiler or linter.
> Update function declarations to support async/await

- src/email-exception.js
Have the EmailException extend Error, so that for example Sentry recognises these errors.
Fixes https://github.com/tschoffelen/react-native-email-link/issues/63
Related: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types
> have EmailException extend Error

- index.ios.js
Noticed that these were missing which would cause Superhuman to just open to the inbox even if you called `openComposer`. Tested each of these params and they work as expected with Superhuman.
> Add params for Superhuman

- index.d.ts
- index.ios.js
This provides apps with more information and enables them to offer user flows like remembering choices for next time. Fixes #52 by returning `null` if the user canceled, but still correctly throwing an error if there's an issue.
> Return the email app that was selected or null

- src/email-exception.js
Now that `EmailException` extends the `Error` class (as per #64), we have to properly initialize `Error`. Otherwise, when you try to throw `EmailException` you end up with `TypeError: undefined is not an object (evaluating '_this.message = message')`.
> Properly initialize the Error class when throwing EmailException

- index.d.ts
The documentation shows usage of these without a passed object param. This is a correction to support that usage with TypeScript. I have tested this locally without issue.
> Make passed object parameter optional

- src/email-exception.js
Make sure we pass on all parameters to the Error base class (such as line number and filename)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#ES5_Custom_Error_Object
> Properly extend Error base class

- README.md
- index.android.js
- index.ios.js
When I call `openCompose` on Android, the body is encoded by default. I would like to have control over that behaviour to avoid having my email body looking like this:
- Added for both iOS and Android an `encodeBody` flag in `options` to encode the body if set to **true**.
- Fixed "Subject" input displaying "null" is no subject was provided.
Note: My linter has updated some of the code, just tell me if you want to revert these changes...
Fixes #76
> Feat: Add encodeBody option to openCompose function

- README.md
- docs/expo.md
- src/ios.js
Yandex Mail is one of the most popular email clients in Russia. It would be nice if this library also supports this client.
The URL scheme: `yandexmail://`
The path to compose a new email: `compose`
It seems that the additional parameters (to, cc, bcc, subject, body) are not supported yet by this app.
> Add Yandex Mail

- docs/expo.md
the domain name for expo is `.dev` and not `.io`
> update expo documentation link to avoid redirect

- index.js
So that the Expo plugin module resolution works. Fixes #96
After a lot of investigation the reason that the Expo plugin module resolution fails is because it can't find a `index.js` file. The module resolution happens in node so it doesn't pick up the `.ios.js` or `.android.js` files.
> Add placeholder index.js file

- src/ios.js
Since iOS 14 (and iPadOS 14) Apple allows users to change the default mail app
Because `mailto://` is used for composing (due to `message://` not supporting any parameters) the title no longer fits the app it opens. This proposal provides a bandaid in the form of an override based on the action type ("default mail client" instead of "Mail" when calling `openComposer`).
> Add title override for Apple Mail

- README.md
- plugin/withEmailLink.js
iOS now seems to require adding the `mailto` scheme to `LSApplicationQueriesSchemes`. Adding it in the README and Expo plugin.
Resolves https://github.com/includable/react-native-email-link/issues/118
> Add mailto scheme

- README.md
- android/src/main/java/agency/flexible/react/modules/email/EmailModule.java
- src/android.js
This pull request adds support for `bcc` and `cc` values to be placed in the `mailto` link on Android. It has been tested w/ the Gmail app on an Android emulator. Documentation updated to reflect that `cc` and `bcc` now available on Android or iOS.
> Support cc and bcc on Android

- android/build.gradle
Trivial change to support AGP 8 as mentioned here: https://github.com/react-native-community/discussions-and-proposals/issues/671
This does not remove package attribute from AndroidManifest to not lose compatibility with AGP < 8 (React Native < 0.71 versions). 
I don't think it's worth maintaining logic to remove that attribute contitionally since it will [only cause a warning to users on AGP 8](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1607191009) and above.
> feat(android): add namespace to support AGP 8

- android/build.gradle
Add support for RN 0.73.
Similar to https://github.com/th3rdwave/react-native-safe-area-context/pull/455
> feat: enable buildFeatures.buildConfig for android gradle plugin 8+

- README.md
- android/src/main/java/agency/flexible/react/modules/email/EmailModule.java
- index.android.js
- index.d.ts
- index.ios.js
- index.js
- src/android.js
- src/ios.js
Thanks for the library!
I recently needed to develop a feature with a list of all available email apps on given device. Your library helped a lot, thanks for that!
BUT! the list needed to be put within some custom UI thus I needed to extend the API and decided to create a PR with my changes, maybe it could be useful for others!
Let me know what you think and if it is a good addition to the library / if anythings needs some tweaking
Have a good day, cheers!
> feat: `getEmailClients` method + `openComposer` accepting pre-selected `app`

- README.md
Hi, one more quick thing. I saw that after merge, there was a linter error caused by a readme file not being correctly formatted. Fixed that :)
> chore: format readme (linter errors)
